version: '3'

services:

  db:
    build: .
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

