spring:
  jpa:
    database: POSTGRESQL
  datasource:
    url: ${PGHOST}
    username: ${PGUSER}
    password: ${PGPASSWORD}
rakutenapp:
  id: ${APP_ID}
appconfig:
  updateIntervalMinutes: 90
  poppingHours: 24
  expireHours: 100
  nPage: 20
  nMaxInsert: 150
