version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Build whole app.
          command: |
            echo 'Build Start...'
            ./gradlew build
            echo 'Build Completed!'
            