version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            date
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create table.
          command: |
            date
            source local_script.sh
            sudo apt install -y postgresql-client || true
            psql --host=localhost -f ./src/main/resources/db/table.sql
      - run:
          name: Build app.
          command: |
            source local_script.sh
            ./gradlew build
            