version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create table.
          command: |
            source local_script.sh
            sudo apt install -y postgresql-client || true
            psql -f ./src/main/resources/db/table.sql
      - run:
          name: Build app.
          command: |
            source local_script.sh
            ./gradlew build

  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: main
