version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
    steps:
      - checkout
      - run:
          name: Create table.
          command: |
            apt install -y postgresql-client || true
            psql -f ./src/main/resource/db/table.sql
      - run:
          name: Build app.
          command: |
            source local_script.sh
            ./gradlew build
            