version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Set up environment variables.
          command: |
            export DB_NAME="testdb"
            export POSTGRES_URL="jdbc:postgresql://localhost:5432/${DB_NAME}"
            export POSTGRES_USER="postgres"
            export POSTGRES_PASS="password"
      - run:
          name: Build whole app.
          command: |
            echo 'Build Start...'
            ./gradlew build
            echo 'Build Completed!'
            