version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/postgres:14.0
        auth:
          username: postgres
          password: password
    steps:
      - checkout
      - run:
          name: Build whole app.
          command: |
            source local_script
            ./gradlew build
            