version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        volumes:
          - ./resource/:/docker-entrypoint-initdb.d
    steps:
      - checkout
      - run:
          name: Build whole app.
          command: |
            source local_script.sh
            ./gradlew build
            